/**
 * Every user-facing string lives here so the UI has no hardcoded copy and a
 * translation layer can be dropped in later without touching components.
 */
export const BRAND = "Niumpi";

export const copy = {
  brand: {
    name: BRAND,
    eyebrow: "Your little companion",
    tagline: "A cozy virtual pet that grows with you.",
    promise: `${BRAND} remembers you, develops a real personality and evolves through the way you care for it.`,
  },
  nav: {
    home: "Home", niumpi: BRAND, room: "Room", memory: "Memory", garden: "Garden",
    games: "Games", shop: "Shop", more: "More", journey: "Journey", evolution: "Evolution",
    cooking: "Cooking", dreams: "Dreams", friends: "Friends", about: "About", seed: "Seed",
    settings: "Settings",
  },
  home: {
    memorySeeds: "Memory Seeds",
    memorySeedsNote: `${BRAND} wants to know you better`,
    personality: "Personality",
    traits: "Traits",
    preferences: "Preferences",
    evolution: "Evolution Journey",
    evolutionNote: "Care, feeding and personality shape Niumpi's future.",
    room: "Your Room",
    roomNote: "Decorate, play and make it cozy!",
    vibe: "Today's vibe",
    snackBar: "Snack Bar",
    snackHint: "Drag a treat to Niumpi",
    cook: "Cook",
    lampOn: "Lamp on",
    lampOff: "Lamp off",
    tuckIn: "Tuck in",
    wakeUp: "Wake up",
    sleeping: "Sleeping",
    dreaming: "Dreaming",
    discovery: "Still learning about you",
    discoveryEmpty: "Still discovering",
    discoveryEmptyNote: "Your care and choices shape who Niumpi becomes.",
    miniGames: "Mini Games",
    miniGamesNote: "Short & fun games to play!",
    cooking: "Cooking",
    cookingNote: "Mix ingredients to create treats",
    dreamDoors: "Dream Doors",
    dreamDoorsNote: "Choose a dream for tonight…",
    friends: "Friends & Visits",
    friendsNote: "Meet other Niumpi!",
    missions: "Today's missions",
    sharedMoments: "shared moments",
    sharedMomentsNote: "So many memories together!",
  },
  stats: {
    fullness: "Fullness", energy: "Energy", joy: "Joy", cleanliness: "Cleanliness",
    bond: "Bond", level: "Level",
    lowFullness: "Hungry", lowEnergy: "Tired", lowJoy: "Needs company", lowCleanliness: "Needs a wash",
  },
  seed: {
    title: "The First Care",
    lead: "Before Niumpi opens their eyes, the seed learns your touch.",
    hatching: "Stay close. It is almost here.",
    nameTitle: "What will you call them?",
    nameLead: "You can change this later — nothing is lost.",
  },
  actions: {
    pet: "Pet", hug: "Hug", feed: "Feed", play: "Play",
    brush: "Brush", wash: "Wash", talk: "Talk", toy: "Toy", tickle: "Tickle",
    dance: "Dance", comfort: "Comfort", sing: "Sing", wake: "Wake",
  },
  states: {
    loading: "Loading…",
    saving: "Saving…",
    saved: "Saved",
    saveFailed: "Could not save — we will try again",
    offline: "Offline — your progress is kept on this device",
    empty: "Nothing here yet",
    locked: "Not open yet",
    owned: "Owned",
    noInventory: "You need more of this",
    maxLevel: "At its best already",
    unavailable: "Unavailable right now",
    error: "Something went wrong. Nothing was lost.",
  },
  about: {
    title: `Why you'll love ${BRAND}`,
    points: [
      { title: "Real personality", note: `${BRAND} remembers you and grows uniquely.`, art: "personality" },
      { title: "Endless things to do", note: "Minigames, cooking, room decor, friends and more.", art: "activities" },
      { title: "Unique evolution", note: "Your care and choices shape who they become.", art: "evolution" },
      { title: "Daily surprises", note: "New memories, items and moments every day.", art: "surprise" },
      { title: "Collect & discover", note: "Adorable items, recipes and magical dreams.", art: "collect" },
      { title: "A cozy digital friend", note: "That brings a little magic to your day.", art: "friend" },
    ],
    playAnywhere: "Play Anywhere",
    playAnywhereNote: `Your ${BRAND}, always with you.`,
    closing: "More than a game — a little world to come back to.",
  },
  safety: {
    seedPrivacy: "These answers stay on your device. You can change or delete any of them.",
    noDeath: `${BRAND} never gets sick from being alone, and never disappears.`,
  },
} as const;

export const moodCopy = {
  excited: { label: "Excited", leaf: "Fast bouncing and sparks" },
  happy: { label: "Happy", leaf: "Calm floating" },
  tired: { label: "Tired", leaf: "Slow sinking" },
  hungry: { label: "Hungry", leaf: "A slight tremble" },
  curious: { label: "Curious", leaf: "Turning and tilting" },
  upset: { label: "Upset", leaf: "Dimmed and low" },
  dreaming: { label: "Dreaming", leaf: "Star motes" },
  evolving: { label: "Evolving", leaf: "Strong glow" },
} as const;
